merge, join , concatenate
pivot table
multi indexing

In [1]:
import pandas as pd

In [2]:
# create two dataFrames
list_x = list(range(9,91,9))
list_x

[9, 18, 27, 36, 45, 54, 63, 72, 81, 90]

In [7]:
list_y = list(range(13,131,13))
list_y

[13, 26, 39, 52, 65, 78, 91, 104, 117, 130]

In [9]:
# create dataframe using two list
df_1=pd.DataFrame({'mult_9':list_x, 'mult_13':list_y})

In [10]:
df_1

   mult_9  mult_13
0       9       13
1      18       26
2      27       39
3      36       52
4      45       65
5      54       78
6      63       91
7      72      104
8      81      117
9      90      130

In [11]:
# create dataframe
df2 = pd.DataFrame({'mult_17':list(range(17,171,17)), 'mult_8':list(range(18,181,18))})

In [12]:
df2

   mult_17  mult_8
0       17      18
1       34      36
2       51      54
3       68      72
4       85      90
5      102     108
6      119     126
7      136     144
8      153     162
9      170     180

In [13]:
# create index colum for df_1
len(df_1)

10

In [14]:
df_1['index'] = range(len(df_1))

In [15]:
df_1

   mult_9  mult_13  index
0       9       13      0
1      18       26      1
2      27       39      2
3      36       52      3
4      45       65      4
5      54       78      5
6      63       91      6
7      72      104      7
8      81      117      8
9      90      130      9

In [16]:
# add index column for df2
df2['index'] = range(len(df2))

In [17]:
df2

   mult_17  mult_8  index
0       17      18      0
1       34      36      1
2       51      54      2
3       68      72      3
4       85      90      4
5      102     108      5
6      119     126      6
7      136     144      7
8      153     162      8
9      170     180      9

In [18]:
# Join -- horizontal join , vertical join
# vertical join - number of columns must be equal
# Horizonal join ---at least one column must be same

In [19]:
# Horizontal join --- merge()
pd.merge(df_1,df2, on='index')

   mult_9  mult_13  index  mult_17  mult_8
0       9       13      0       17      18
1      18       26      1       34      36
2      27       39      2       51      54
3      36       52      3       68      72
4      45       65      4       85      90
5      54       78      5      102     108
6      63       91      6      119     126
7      72      104      7      136     144
8      81      117      8      153     162
9      90      130      9      170     180

In [22]:
# load village dataset
v1= pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\village1.csv")
v1.head(2)

          Name                Address  Age  BankBalanceNPR
0  Hari Gurung  Ghandruk Ward 1 Kaski   33          320000
1  Maya Gurung  Ghandruk Ward 2 Kaski   28          210500

In [24]:
v2=pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\village2.csv")
v2.head(2)

                 Name                       Address  Age  BankBalanceNPR
0  Ram Bahadur Tamang  Bhimtar Ward 1 Sindhupalchok   34          245000
1    Sita Maya Tamang  Bhimtar Ward 2 Sindhupalchok   29          185500

In [27]:
# vertical join -- all column are same
pd.concat([v1,v2])

                 Name                       Address  Age  BankBalanceNPR
0         Hari Gurung         Ghandruk Ward 1 Kaski   33          320000
1         Maya Gurung         Ghandruk Ward 2 Kaski   28          210500
2       Bikash Gurung         Ghandruk Ward 3 Kaski   45          680000
3        Anita Gurung         Ghandruk Ward 1 Kaski   36          455000
4       Ramesh Gurung         Ghandruk Ward 4 Kaski   24          125000
5       Sunita Gurung         Ghandruk Ward 2 Kaski   30          298700
6       Deepak Gurung         Ghandruk Ward 5 Kaski   51          940000
7        Laxmi Gurung         Ghandruk Ward 3 Kaski   26          175300
8       Suresh Gurung         Ghandruk Ward 4 Kaski   41          560000
9       Kabita Gurung         Ghandruk Ward 5 Kaski   38          389500
0  Ram Bahadur Tamang  Bhimtar Ward 1 Sindhupalchok   34          245000
1    Sita Maya Tamang  Bhimtar Ward 2 Sindhupalchok   29          185500
2          Kiran Lama  Bhimtar Ward 3 Sindhupalchok   42          520000
3         Pema Sherpa  Bhimtar Ward 1 Sindhupalchok   37          410250
4         Nima Tamang  Bhimtar Ward 4 Sindhupalchok   25           98000
5           Mina Lama  Bhimtar Ward 2 Sindhupalchok   31          275400
6         Dawa Sherpa  Bhimtar Ward 5 Sindhupalchok   48          735000
7         Rita Tamang  Bhimtar Ward 3 Sindhupalchok   27          162800
8          Sonam Lama  Bhimtar Ward 4 Sindhupalchok   39          340900
9      Tsering Sherpa  Bhimtar Ward 5 Sindhupalchok   55          890000

# pivot tables

In [33]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
data = pd.read_excel(r"D:\my project\codeit_datascience\data_science\regression\data science\Ecommerce Sales Data.xlsx")
data.head(2)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [36]:
data.columns

Index(['Row ID', 'Order ID', 'Year', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [39]:
data['State'].unique()

<StringArray>
[            'Kentucky',           'California',              'Florida',
       'North Carolina',           'Washington',                'Texas',
            'Wisconsin',                 'Utah',             'Nebraska',
         'Pennsylvania',             'Illinois',            'Minnesota',
             'Michigan',             'Delaware',              'Indiana',
             'New York',              'Arizona',             'Virginia',
            'Tennessee',              'Alabama',       'South Carolina',
               'Oregon',             'Colorado',                 'Iowa',
                 'Ohio',             'Missouri',             'Oklahoma',
           'New Mexico',            'Louisiana',          'Connecticut',
           'New Jersey',        'Massachusetts',              'Georgia',
               'Nevada',         'Rhode Island',          'Mississippi',
             'Arkansas',              'Montana',        'New Hampshire',
             'Maryland', 'District of Columbia',               'Kansas',
              'Vermont',                'Maine',         'South Dakota',
                'Idaho',         'North Dakota',              'Wyoming',
        'West Virginia']
Length: 49, dtype: str

In [41]:
data.State.nunique()

49

In [42]:
data.groupby('State')['Sales'].sum()

State
Alabama                  19510.6400
Arizona                  35282.0010
Arkansas                 11678.1300
California              457687.6315
Colorado                 32108.1180
Connecticut              13384.3570
Delaware                 27451.0690
District of Columbia      2865.0200
Florida                  89473.7080
Georgia                  49095.8400
Idaho                     4382.4860
Illinois                 80166.1010
Indiana                  53555.3600
Iowa                      4579.7600
Kansas                    2914.3100
Kentucky                 36591.7500
Louisiana                 9217.0300
Maine                     1270.5300
Maryland                 23705.5230
Massachusetts            28634.4340
Michigan                 76269.6140
Minnesota                29863.1500
Mississippi              10771.3400
Missouri                 22205.1500
Montana                   5589.3520
Nebraska                  7464.9300
Nevada                   16729.1020
New Hampshire             7292.5240
New Jersey               35764.3120
New Mexico                4783.5220
New York                310876.2710
North Carolina           55603.1640
North Dakota               919.9100
Ohio                     78258.1360
Oklahoma                 19683.3900
Oregon                   17431.1500
Pennsylvania            116511.9140
Rhode Island             22627.9560
South Carolina            8481.7100
South Dakota              1315.5600
Tennessee                30661.8730
Texas                   170188.0458
Utah                     11220.0560
Vermont                   8929.3700
Virginia                 70636.7200
Washington              138641.2700
West Virginia             1209.8240
Wisconsin                32114.6100
Wyoming                   1603.1360
Name: Sales, dtype: float64

In [43]:
# pivot table -- pivot_table()
pd.pivot_table(data=data, values='Sales', index='State', aggfunc='sum')

                            Sales
State
Alabama                19510.6400
Arizona                35282.0010
Arkansas               11678.1300
California            457687.6315
Colorado               32108.1180
Connecticut            13384.3570
Delaware               27451.0690
District of Columbia    2865.0200
Florida                89473.7080
Georgia                49095.8400
Idaho                   4382.4860
Illinois               80166.1010
Indiana                53555.3600
Iowa                    4579.7600
Kansas                  2914.3100
Kentucky               36591.7500
Louisiana               9217.0300
Maine                   1270.5300
Maryland               23705.5230
Massachusetts          28634.4340
Michigan               76269.6140
Minnesota              29863.1500
Mississippi            10771.3400
Missouri               22205.1500
Montana                 5589.3520
Nebraska                7464.9300
Nevada                 16729.1020
New Hampshire           7292.5240
New Jersey             35764.3120
New Mexico              4783.5220
New York              310876.2710
North Carolina         55603.1640
North Dakota             919.9100
Ohio                   78258.1360
Oklahoma               19683.3900
Oregon                 17431.1500
Pennsylvania          116511.9140
Rhode Island           22627.9560
South Carolina          8481.7100
South Dakota            1315.5600
Tennessee              30661.8730
Texas                 170188.0458
Utah                   11220.0560
Vermont                 8929.3700
Virginia               70636.7200
Washington            138641.2700
West Virginia           1209.8240
Wisconsin              32114.6100
Wyoming                 1603.1360

In [44]:
data.Category.unique()

<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [47]:
pd.pivot_table(
    data=data,
    values='Sales',
    index='State',
    columns='Category',
    aggfunc=['min','max']
)

                           min                                  max  \
Category             Furniture Office Supplies Technology Furniture
State
Alabama                  8.960           3.620     25.980  1819.860
Arizona                  4.272           1.408      7.160  1272.630
Arkansas                 8.920           4.300     26.850  1067.940
California               3.480           1.440      0.990  3610.848
Colorado                 4.224           1.080     15.992  1325.760
Connecticut             22.200           3.520     14.990  1133.350
Delaware                 9.940           3.380     19.980  1268.820
District of Columbia    37.680           9.640   1379.920  1267.530
Florida                  2.784           1.167      2.376  2803.920
Georgia                  7.040           1.780      5.950  1628.820
Idaho                   35.000           3.304     89.970  1128.390
Illinois                 1.892           0.836      2.376   913.430
Indiana                  2.910           2.520      1.980  2678.940
Iowa                    14.910           5.400    207.000  1408.100
Kansas                  40.560           5.760     34.950    70.560
Kentucky                13.280           2.610     18.000  2573.820
Louisiana                8.010           3.890     29.000  1504.520
Maine                  109.480           8.260     67.980   109.480
Maryland                10.560           1.640     49.080  1779.900
Massachusetts            9.480           3.150     23.180  1628.820
Michigan                 5.470           2.200      8.780  3504.900
Minnesota                6.160           3.750     19.990  2567.840
Mississippi              6.160           7.890     38.970  2430.080
Missouri                 9.680           7.640     21.200  1024.380
Montana                 63.980           6.096    105.584    63.980
Nebraska                15.920           5.040     29.970  1336.440
Nevada                  14.560           3.640     58.580  1685.880
New Hampshire           21.120          14.820     29.990  1053.164
New Jersey               8.280           3.760     31.800  2154.900
New Mexico              41.370           4.170     23.976   883.840
New York                 6.160           1.240      2.970  4228.704
North Carolina           4.712           1.752      7.920  4297.644
North Dakota               NaN           2.480        NaN       NaN
Ohio                     4.656           1.448      2.970  1548.990
Oklahoma                30.360           3.520      5.500  1805.880
Oregon                  11.032           1.080     28.400  1487.040
Pennsylvania             2.960           0.852     10.312  4416.174
Rhode Island            14.760           2.220     69.980  1604.900
South Carolina          14.760           6.460     62.910  1690.040
South Dakota           141.960           6.540      2.970   182.940
Tennessee                9.656           2.469      1.584  2314.116
Texas                    1.988           0.444      5.544  2453.430
Utah                    25.160           4.960     16.776  1406.860
Vermont                715.200           2.040     99.980  4404.900
Virginia                 8.800           2.840     20.700  2275.500
Washington               4.180           1.344      7.992  3393.680
West Virginia          673.344           6.240        NaN   673.344
Wisconsin                5.820           1.810      1.980  2807.840
Wyoming               1603.136             NaN        NaN  1603.136


Category             Office Supplies Technology
State
Alabama                      900.080   3040.000
Arizona                     1113.024   1879.960
Arkansas                    1793.980    881.930
California                  8187.650   4799.984
Colorado                    1332.496   2549.985
Connecticut                  579.510    832.930
Delaware                    2934.330  10499.970
District of Columbia          40.080   1379.920
Florida                     1801.632  22638.480
Georgia                     6354.950   2999.950
Idaho                        477.150    304.776
Illinois                    1889.990   2799.960
Indiana                     2405.200  17499.950
Iowa                         115.840    404.940
Kansas                       360.380    273.960
Kentucky                    1577.940   3080.000
Louisiana                   1665.620    659.900
Maine                        259.740    437.850
Maryland                    2541.980   1259.930
Massachusetts               1737.180   1199.980
Michigan                    9892.740   3059.982
Minnesota                   9449.950    655.900
Mississippi                  511.840    659.970
Missouri                    4164.050   4899.930
Montana                     1126.020   2999.950
Nebraska                     750.680   2479.960
Nevada                      4535.976   2396.400
New Hampshire                671.940   2249.910
New Jersey                  2625.120   9099.930
New Mexico                   288.240    595.000
New York                    4355.168  11199.968
North Carolina              1633.188   7999.980
North Dakota                 704.760        NaN
Ohio                        1006.056   4499.985
Oklahoma                    1117.920   1439.920
Oregon                       718.640    859.200
Pennsylvania                4663.736   8399.976
Rhode Island                2079.400   5399.910
South Carolina               887.840    629.950
South Dakota                 416.320    389.970
Tennessee                   1614.582   2239.936
Texas                       3930.072   8159.952
Utah                        1089.750   1499.950
Vermont                     1564.290   1294.750
Virginia                    4164.050   8749.950
Washington                  3266.376  13999.960
West Virginia                447.840        NaN
Wisconsin                   1089.750   1649.750
Wyoming                          NaN        NaN

In [48]:
data.head(2)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [52]:
pd.pivot_table(
    data=data,
    values='Sales',
    index='State',
    columns=['Category','Sub-Category'],
    aggfunc='sum'
)

Category               Furniture                                    \
Sub-Category           Bookcases     Chairs Furnishings     Tables
State
Alabama                      NaN   3915.540      40.480   2376.460
Arizona                 519.2130   6499.080    2511.648   3995.350
Arkansas                638.8200   1673.280     573.490    301.960
California            27558.5215  63079.368   19996.480  45430.232
Colorado               1583.5230   8244.816    1957.568   1457.130
Connecticut            1682.7400   2782.420     457.470    252.357
Delaware               2051.7300   1559.920     637.390    510.279
District of Columbia         NaN   1267.530      79.050        NaN
Florida                2587.0560  11168.816    3746.192   5484.974
Georgia                3793.5000   1858.160    1805.080    864.740
Idaho                        NaN    338.352     432.320   1824.810
Illinois               4282.6980  14563.178    2877.976   6550.670
Indiana                      NaN   6463.390    1514.480   3518.840
Iowa                         NaN   1408.100      49.490   1184.720
Kansas                       NaN        NaN     111.120        NaN
Kentucky                261.9600   9233.570    1788.370    842.940
Louisiana               387.7000    802.340     182.490   1590.500
Maine                        NaN        NaN     109.480        NaN
Maryland                881.8200   4329.910    3147.720    789.803
Massachusetts          1873.7200   4245.600     833.740   3966.004
Michigan                810.2000  13878.060    1916.260   5716.580
Minnesota                    NaN   6079.370     231.520   1300.460
Mississippi             504.9000    866.400     430.490   2516.060
Missouri                212.9400     60.890     941.080   1721.540
Montana                      NaN        NaN      63.980        NaN
Nebraska                     NaN    563.940    1380.760        NaN
Nevada                  141.9600    674.352     463.380   3355.480
New Hampshire                NaN        NaN     833.310   1053.164
New Jersey             2275.8800   2661.900     950.970    418.292
New Mexico                   NaN   1114.192     587.220        NaN
New York              22777.1440  46634.247   10182.320  13779.018
North Carolina          959.0560   2723.592    1791.104   9681.732
North Dakota                 NaN        NaN         NaN        NaN
Ohio                   2077.7050  10145.702    4088.624   7887.114
Oklahoma                341.9600   3963.380    1444.920   2533.840
Oregon                  356.6460   3841.160     468.464   1671.860
Pennsylvania           5230.7550  18724.174    7347.816   8052.186
Rhode Island            562.9400   3194.080     403.490   1758.246
South Carolina               NaN   2537.940     540.310        NaN
South Dakota            141.9600    182.940         NaN        NaN
Tennessee               518.2400   5074.888    1699.248   6214.356
Texas                 14493.4588  26572.448    3766.724  15760.661
Utah                   2699.8000        NaN     165.170   1957.380
Vermont                4404.9000    715.200         NaN        NaN
Virginia               1248.1300   5321.920    4709.430  14042.470
Washington             3144.4600  16386.872    3426.500  25062.320
West Virginia                NaN        NaN         NaN    673.344
Wisconsin              3873.9600  11494.950    1020.040    867.660
Wyoming                      NaN   1603.136         NaN        NaN

Category             Office Supplies                                           \
Sub-Category              Appliances       Art    Binders Envelopes Fasteners
State
Alabama                      208.160   301.210    466.820   105.840     3.620
Arizona                      774.432  1389.152   2185.353   214.520   101.232
Arkansas                         NaN    78.300   2889.830   311.700    42.670
California                 24175.920  5495.660  28473.168  3237.340   479.530
Colorado                    1367.296   210.624    508.968    75.600    44.520
Connecticut                 1479.180   191.660    371.870    10.860       NaN
Delaware                     140.420   535.350   2434.030   299.230    26.180
District of Columbia             NaN    56.660      9.640       NaN       NaN
Florida                     3558.440   710.920   3690.498   211.000    49.256
Georgia                     3432.150   526.680  11672.320   446.570    15.120
Idaho                        227.840       NaN     71.656       NaN       NaN
Illinois                     974.720   930.032   4538.546   384.104   141.336
Indiana                     4160.150   389.190   4011.880   889.560     8.460
Iowa                             NaN   146.580    247.960    13.400    45.920
Kansas                        81.960   162.720    611.920       NaN    24.050
Kentucky                    1335.620   350.720   3695.820   105.350    76.060
Louisiana                     17.340   129.500    628.520    62.300       NaN
Maine                        101.960       NaN     38.100       NaN       NaN
Maryland                    1589.160   433.690   3225.050   337.150    27.320
Massachusetts               3347.750   226.050   2105.190       NaN    51.160
Michigan                    4324.149  1004.860  22821.970   310.020   109.500
Minnesota                   2844.130   102.810  12470.240    30.560    42.900
Mississippi                  615.550   606.660    966.850    91.370    35.020
Missouri                    3670.430   239.620   1875.620    71.180       NaN
Montana                          NaN       NaN    502.368       NaN       NaN
Nebraska                     500.570    19.460    128.230       NaN    57.640
Nevada                        95.980   214.280   4897.184       NaN     4.710
New Hampshire                 33.280   266.400    763.480       NaN    14.820
New Jersey                  4204.360   742.800   3529.520   153.700    54.120
New Mexico                       NaN   276.700    125.632    28.400       NaN
New York                   13276.380  2983.600  32456.912  1776.830   286.510
North Carolina              4137.552   603.392   2562.321   431.144    66.336
North Dakota                     NaN   181.840     25.900       NaN     7.410
Ohio                        4807.536   840.104   1917.087   562.000   204.896
Oklahoma                    1491.220    58.910    445.440   407.400       NaN
Oregon                       535.768   461.760    281.064    49.520    20.024
Pennsylvania                4663.280  1152.160   6266.058  1234.064   154.712
Rhode Island                   2.220    49.250    292.420       NaN       NaN
South Carolina                   NaN    35.440    515.080   318.850    43.410
South Dakota                 416.320       NaN    114.510       NaN     6.540
Tennessee                   1914.984   436.480   5148.042   177.352    86.664
Texas                       2407.814  2369.528   9042.676  2530.648   332.464
Utah                        1089.750   100.050    759.592       NaN    10.000
Vermont                      542.940     8.040        NaN     2.040       NaN
Virginia                    4305.530   876.320   4794.240  1084.080    85.160
Washington                  1969.350  1063.840  18156.128   512.720   263.200
West Virginia                    NaN       NaN     88.640       NaN       NaN
Wisconsin                   2710.570   159.790    588.390       NaN     1.810
Wyoming                          NaN       NaN        NaN       NaN       NaN

Category                                                         Technology  \
Sub-Category            Labels      Paper    Storage   Supplies Accessories
State
Alabama                506.490    883.020   1249.410    484.510    2322.830
Arizona                 27.464   2440.760   2590.384    282.528    3396.160
Arkansas                 7.310    805.520    430.000        NaN    1788.440
California            2899.140  16757.950  45112.290  15720.950   37255.010
Colorado                17.960    883.216   3387.168   1403.400    2287.992
Connecticut             33.430    788.220   2428.260    114.860     657.690
Delaware                74.130    440.770   4179.420        NaN     561.690
District of Columbia       NaN     72.220        NaN        NaN         NaN
Florida                385.808   2425.560   7419.256   1067.896    5861.944
Georgia                244.920   2957.240   7381.290     39.520    3657.870
Idaho                      NaN    172.860    477.150        NaN      89.970
Illinois               224.872   3455.816   9080.328    178.152    5535.696
Indiana                276.210   1879.520   4120.430        NaN    2279.030
Iowa                       NaN    315.810     13.480        NaN         NaN
Kansas                  18.900    303.000    393.670    357.930      92.350
Kentucky               363.400   1058.550   4822.430     86.320    2976.300
Louisiana               11.070    103.680    805.130   1665.620    1667.800
Maine                      NaN    259.740        NaN        NaN     323.400
Maryland               171.510   1039.350   3541.980     25.020    1123.810
Massachusetts          165.650   1774.090   4288.780     30.070     896.910
Michigan               880.560   2010.740   6187.480     74.480    4932.550
Minnesota              161.050    319.880   3397.730     37.240    1520.380
Mississippi             14.620    725.280    575.810        NaN    2009.660
Missouri                14.940    301.810   1791.940   4216.640    1021.680
Montana                 14.620     41.000   1304.450        NaN     217.440
Nebraska                14.400    332.790   1164.500     16.900     239.940
Nevada                  14.940    317.780   1325.850     86.200     229.550
New Hampshire           41.160    284.880    337.300     27.930    2811.850
New Jersey              66.340   1421.760   4669.080    114.430    1023.560
New Mexico              18.450    625.780    279.660     29.560    1163.800
New York              1290.570   8457.260  26928.350   2563.630   19597.540
North Carolina         229.424   2594.264   3438.088    302.040    3506.632
North Dakota               NaN        NaN    704.760        NaN         NaN
Ohio                   161.840   2146.288   7264.440    478.808    8222.872
Oklahoma                64.240    196.620   2345.050     21.960    1817.470
Oregon                 902.112    953.352   1991.120     76.744    1160.304
Pennsylvania           598.304   2378.304  11784.624   6710.208    7299.280
Rhode Island               NaN    569.680   4626.060    695.160    2209.760
South Carolina             NaN    331.850   2567.210        NaN     138.890
South Dakota            34.850        NaN        NaN     25.500     392.940
Tennessee              115.368   1060.320   3310.856     97.792     410.568
Texas                  583.600   6983.456  15723.584   4516.760   11328.560
Utah                    30.150   1152.280    901.580     44.400     194.730
Vermont                    NaN     92.200   1564.290        NaN     305.010
Virginia               474.770   1205.700   3768.580   4575.230    2935.820
Washington            1153.890   3318.740  13163.200    483.340   15119.160
West Virginia              NaN    447.840        NaN        NaN         NaN
Wisconsin              177.850   1392.460   1007.160     21.810    4795.480
Wyoming                    NaN        NaN        NaN        NaN         NaN

Category
Sub-Category            Copiers   Machines     Phones
State
Alabama                 899.970   3040.000   2706.280
Arizona                     NaN    965.949   7388.776
Arkansas                    NaN        NaN   2136.810
California            24559.520  29492.016  67964.536
Colorado                439.992   3313.689   4924.656
Connecticut                 NaN        NaN   2133.340
Delaware              10499.970     65.970   3434.590
District of Columbia        NaN   1379.920        NaN
Florida                1439.968  24573.940  15092.184
Georgia                2999.950    396.000   7004.730
Idaho                       NaN        NaN    747.528
Illinois               5919.888   3756.305  16771.784
Indiana               18499.930     83.900   5460.390
Iowa                        NaN        NaN   1154.300
Kansas                      NaN        NaN    756.690
Kentucky               1399.980   3080.000   5114.360
Louisiana                   NaN    479.970    683.070
Maine                       NaN        NaN    437.850
Maryland                    NaN    464.970   2577.260
Massachusetts          1199.980        NaN   3629.740
Michigan               1149.970   3410.955   6731.280
Minnesota               549.990        NaN    774.890
Mississippi                 NaN        NaN    812.670
Missouri               5499.920        NaN    564.920
Montana                2999.950        NaN    445.544
Nebraska                    NaN        NaN   3045.800
Nevada                      NaN   2396.400   2511.056
New Hampshire               NaN        NaN    824.950
New Jersey                  NaN   9899.850   3577.750
New Mexico                  NaN        NaN    534.128
New York              17199.840  43183.500  47502.620
North Carolina          959.968  12620.655   8995.864
North Dakota                NaN        NaN        NaN
Ohio                   3839.934   8978.238  14634.948
Oklahoma                    NaN        NaN   4550.980
Oregon                      NaN    209.916   4451.336
Pennsylvania          13079.868   2133.717  19702.404
Rhode Island           7399.870        NaN    864.780
South Carolina              NaN        NaN   1452.730
South Dakota                NaN        NaN        NaN
Tennessee                   NaN    740.475   3656.240
Texas                  5639.872  19546.224  28589.568
Utah                   1499.950        NaN    615.224
Vermont                     NaN        NaN   1294.750
Virginia               1599.920   8959.920  10649.500
Washington            20249.830   6066.152   9101.568
West Virginia               NaN        NaN        NaN
Wisconsin                   NaN        NaN   4002.680
Wyoming                     NaN        NaN        NaN

In [60]:
# create pivot table to show sales summary of each customers
pd.pivot_table(
    data=data,
    values='Sales',
    index=['Region','State','Sub-Category'],
    columns='Category',
    aggfunc='sum'
)

Category                         Furniture  Office Supplies  Technology
Region  State      Sub-Category
Central Illinois   Accessories         NaN              NaN    5535.696
                   Appliances          NaN          974.720         NaN
                   Art                 NaN          930.032         NaN
                   Binders             NaN         4538.546         NaN
                   Bookcases      4282.698              NaN         NaN
...                                    ...              ...         ...
West    Washington Phones              NaN              NaN    9101.568
                   Storage             NaN        13163.200         NaN
                   Supplies            NaN          483.340         NaN
                   Tables        25062.320              NaN         NaN
        Wyoming    Chairs         1603.136              NaN         NaN

[656 rows x 3 columns]

# indexing and multi indexing

In [61]:
data.head(2)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [62]:
# indexing: It is a column that uniquely identify a record in a table.
# uses of index: sort, search, filter, identify

In [63]:
# set_index() -- create a index()
data.drop('Row ID', axis=1, inplace=True)

In [64]:
data.head(2)

,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [65]:
data['Order ID'].nunique()

5009

In [66]:
data.shape

(9994, 21)

In [67]:
# here, order ID -- unique are only 5009 
# but shape of dataset is -- 9994 rows so, order ID cannot be index.
# its better to create new 'index' column

In [68]:
# length of dataset
len(data)

9994

In [69]:
# crate index column
data['index']=range(len(data))

In [70]:
data.head(2)

,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,index
0,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136,0
1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820,1

In [71]:
data.index.nunique()

9994

In [74]:
# set index column as 'index'
data.set_index('index', inplace=True)

In [75]:
data.head(2)

,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
index,,,,,,,,,,,,,,,,,,,,,
0,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [78]:
# reset index
data=data.reset_index()

In [79]:
data.head(2)

,index,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,0,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [80]:
# Multiple index using customer name and city

In [81]:
data.set_index(['Customer Name','City'])

                                  index        Order ID  Year  \
Customer Name    City
Claire Gute      Henderson            0  CA-2013-152156  2013
                 Henderson            1  CA-2013-152156  2013
Darrin Van Huff  Los Angeles          2  CA-2013-138688  2013
Sean O'Donnell   Fort Lauderdale      3  US-2012-108966  2012
                 Fort Lauderdale      4  US-2012-108966  2012
...                                 ...             ...   ...
Tom Boeckenhauer Miami             9989  CA-2011-110422  2011
Dave Brooks      Costa Mesa        9990  CA-2014-121258  2014
                 Costa Mesa        9991  CA-2014-121258  2014
                 Costa Mesa        9992  CA-2014-121258  2014
Chris Cortes     Westminster       9993  CA-2014-119914  2014

                                           Order Date            Ship Date  \
Customer Name    City
Claire Gute      Henderson        2013-09-11 00:00:00  2013-12-11 00:00:00
                 Henderson        2013-09-11 00:00:00  2013-12-11 00:00:00
Darrin Van Huff  Los Angeles                6/13/2013            6/17/2013
Sean O'Donnell   Fort Lauderdale  2012-11-10 00:00:00           10/18/2012
                 Fort Lauderdale  2012-11-10 00:00:00           10/18/2012
...                                               ...                  ...
Tom Boeckenhauer Miami                      1/22/2011            1/24/2011
Dave Brooks      Costa Mesa                 2/27/2014  2014-04-03 00:00:00
                 Costa Mesa                 2/27/2014  2014-04-03 00:00:00
                 Costa Mesa                 2/27/2014  2014-04-03 00:00:00
Chris Cortes     Westminster      2014-05-05 00:00:00  2014-10-05 00:00:00

                                       Ship Mode Customer ID    Segment  \
Customer Name    City
Claire Gute      Henderson          Second Class    CG-12520   Consumer
                 Henderson          Second Class    CG-12520   Consumer
Darrin Van Huff  Los Angeles        Second Class    DV-13045  Corporate
Sean O'Donnell   Fort Lauderdale  Standard Class    SO-20335   Consumer
                 Fort Lauderdale  Standard Class    SO-20335   Consumer
...                                          ...         ...        ...
Tom Boeckenhauer Miami              Second Class    TB-21400   Consumer
Dave Brooks      Costa Mesa       Standard Class    DB-13060   Consumer
                 Costa Mesa       Standard Class    DB-13060   Consumer
                 Costa Mesa       Standard Class    DB-13060   Consumer
Chris Cortes     Westminster        Second Class    CC-12220   Consumer

                                        Country       State  Postal Code  \
Customer Name    City
Claire Gute      Henderson        United States    Kentucky        42420
                 Henderson        United States    Kentucky        42420
Darrin Van Huff  Los Angeles      United States  California        90036
Sean O'Donnell   Fort Lauderdale  United States     Florida        33311
                 Fort Lauderdale  United States     Florida        33311
...                                         ...         ...          ...
Tom Boeckenhauer Miami            United States     Florida        33180
Dave Brooks      Costa Mesa       United States  California        92627
                 Costa Mesa       United States  California        92627
                 Costa Mesa       United States  California        92627
Chris Cortes     Westminster      United States  California        92683

                                 Region       Product ID         Category  \
Customer Name    City
Claire Gute      Henderson        South  FUR-BO-10001798        Furniture
                 Henderson        South  FUR-CH-10000454        Furniture
Darrin Van Huff  Los Angeles       West  OFF-LA-10000240  Office Supplies
Sean O'Donnell   Fort Lauderdale  South  FUR-TA-10000577        Furniture
                 Fort Lauderdale  South  OFF-ST-10000760  Office Supplies
...                                 ...              ...              ...
Tom Boeckenhauer Miami            South  FUR-FU-10001889        Furniture
Dave Brooks      Costa Mesa        West  FUR-FU-10000747        Furniture
                 Costa Mesa        West  TEC-PH-10003645       Technology
                 Costa Mesa        West  OFF-PA-10004041  Office Supplies
Chris Cortes     Westminster       West  OFF-AP-10002684  Office Supplies

                                 Sub-Category  \
Customer Name    City
Claire Gute      Henderson          Bookcases
                 Henderson             Chairs
Darrin Van Huff  Los Angeles           Labels
Sean O'Donnell   Fort Lauderdale       Tables
                 Fort Lauderdale      Storage
...                                       ...
Tom Boeckenhauer Miami            Furnishings
Dave Brooks      Costa Mesa       Furnishings
                 Costa Mesa            Phones
                 Costa Mesa             Paper
Chris Cortes     Westminster       Appliances

                                                                       Product Name  \
Customer Name    City
Claire Gute      Henderson                        Bush Somerset Collection Bookcase
                 Henderson        Hon Deluxe Fabric Upholstered Stacking Chairs,...
Darrin Van Huff  Los Angeles      Self-Adhesive Address Labels for Typewriters b...
Sean O'Donnell   Fort Lauderdale      Bretford CR4500 Series Slim Rectangular Table
                 Fort Lauderdale                     Eldon Fold 'N Roll Cart System
...                                                                             ...
Tom Boeckenhauer Miami                                       Ultra Door Pull Handle
Dave Brooks      Costa Mesa       Tenex B1-RE Series Chair Mats for Low Pile Car...
                 Costa Mesa                                   Aastra 57i VoIP phone
                 Costa Mesa       It's Hot Message Books with Stickers, 2 3/4" x 5"
Chris Cortes     Westminster      Acco 7-Outlet Masterpiece Power Center, Wihtou...

                                     Sales  Quantity  Discount    Profit
Customer Name    City
Claire Gute      Henderson        261.9600         2      0.00   41.9136
                 Henderson        731.9400         3      0.00  219.5820
Darrin Van Huff  Los Angeles       14.6200         2      0.00    6.8714
Sean O'Donnell   Fort Lauderdale  957.5775         5      0.45 -383.0310
                 Fort Lauderdale   22.3680         2      0.20    2.5164
...                                    ...       ...       ...       ...
Tom Boeckenhauer Miami             25.2480         3      0.20    4.1028
Dave Brooks      Costa Mesa        91.9600         2      0.00   15.6332
                 Costa Mesa       258.5760         2      0.20   19.3932
                 Costa Mesa        29.6000         4      0.00   13.3200
Chris Cortes     Westminster      243.1600         2      0.00   72.9480

[9994 rows x 20 columns]

In [82]:
df = data.set_index(['Customer Name','City'])

In [83]:
df.head(2)

                         index        Order ID  Year           Order Date  \
Customer Name City
Claire Gute   Henderson      0  CA-2013-152156  2013  2013-09-11 00:00:00
              Henderson      1  CA-2013-152156  2013  2013-09-11 00:00:00

                                   Ship Date     Ship Mode Customer ID  \
Customer Name City
Claire Gute   Henderson  2013-12-11 00:00:00  Second Class    CG-12520
              Henderson  2013-12-11 00:00:00  Second Class    CG-12520

                          Segment        Country     State  Postal Code  \
Customer Name City
Claire Gute   Henderson  Consumer  United States  Kentucky        42420
              Henderson  Consumer  United States  Kentucky        42420

                        Region       Product ID   Category Sub-Category  \
Customer Name City
Claire Gute   Henderson  South  FUR-BO-10001798  Furniture    Bookcases
              Henderson  South  FUR-CH-10000454  Furniture       Chairs

                                                              Product Name  \
Customer Name City
Claire Gute   Henderson                  Bush Somerset Collection Bookcase
              Henderson  Hon Deluxe Fabric Upholstered Stacking Chairs,...

                          Sales  Quantity  Discount    Profit
Customer Name City
Claire Gute   Henderson  261.96         2       0.0   41.9136
              Henderson  731.94         3       0.0  219.5820