# regression

    'DecisionTreeRegressor'
    'RandomForestRegressor'
    'SVR'
    'KNeighborsRegressor'
    'LinearRegression'

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = sns.load_dataset('mpg')
data.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320

In [3]:
data.drop(['origin','name'], axis=1, inplace=True)

In [4]:
data.head(2)

    mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70

In [5]:
data.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
dtype: int64

In [6]:
data = data.dropna()
data.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
dtype: int64

In [7]:
# split X and y parameters
X = data.drop('mpg',axis=1)
y = data['mpg']

In [8]:
# get train and test data
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [19]:
# train with the following regression 
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression

In [20]:
models_name = ['dt','rf','svr','knr','lr']

In [23]:
mdls = {
    'DecisionTreeRegressor':DecisionTreeRegressor(),
    'RandomForestRegressor':RandomForestRegressor(),
    'SVR':SVR(),
    'KNeighborsRegressor':KNeighborsRegressor(),
    'LinearRegression':LinearRegression(),
}

In [26]:
import joblib

In [27]:
# train the model adn check the r2 score
from sklearn.metrics import r2_score
for name, model in mdls.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    rs = r2_score(y_test,y_pred)
    joblib.dump(model,f"{name}.pkl")
    print(f"{name}: {rs}")

DecisionTreeRegressor: 0.7504939030768344
RandomForestRegressor: 0.8840458579761657
SVR: 0.7033359011144167
KNeighborsRegressor: 0.6521862291798177
LinearRegression: 0.7942349075428587

In [25]:
# among all 'rf' random forest regression has the accuracy of 88% better than other
# we choose the 'RandomForestRegressor' model
# save the model